[TIN-XXX] Solr management from the CMS
zicht/solr-bundle pull request #34
Opened 2019-08-22 14:39 UTC by wtfzdotnet

2019-08-23 06:53 UTC, erik-zicht commented on src/Zicht/Bundle/SolrBundle/Manager/SynonymManager.php
> + * @author Gerard van Helden <gerard@zicht.nl>
?

2019-08-23 06:55 UTC, erik-zicht commented on src/Zicht/Bundle/SolrBundle/Solr/QueryBuilder/StopWord.php
> +class StopWord implements RequestBuilderInterface, ResponseHandlerInterface
Deze mag er uit zo te zien

2019-08-27 16:10 UTC, 7ochem requested changes

2019-08-27 16:10 UTC, 7ochem commented on src/Zicht/Bundle/SolrBundle/Admin/StopWordAdmin.php
> +     * @{inheritDoc}
Dit moet `{@inheritDoc}` zijn. Even overal checken

2019-08-27 16:10 UTC, 7ochem commented on src/Zicht/Bundle/SolrBundle/Admin/StopWordAdmin.php
> +    private function getManagedFieldOptions()
Mist een doc comment

2019-08-27 16:10 UTC, 7ochem commented on src/Zicht/Bundle/SolrBundle/Admin/SynonymAdmin.php
> +    private function getManagedFieldOptions()
Mist een doc comment

2019-08-27 16:10 UTC, 7ochem commented on src/Zicht/Bundle/SolrBundle/Entity/StopWord.php
> +    public function setValue(?string $value): void
Versie 3 van de Solr bundle zou ook nog steeds compatible moeten zijn met PHP 5.6, zie composer.json: `"require": { "php": "^5.6|^7",`
Scalar typehints zijn dus helaas niet mogelijk

2019-09-16 11:21 UTC, erik-zicht approved these changes

2019-09-16 11:23 UTC, 7ochem approved these changes

2019-09-16 11:24 UTC, 7ochem commented
Which version is this going to be? 3.4.0? And you will also merge it through to 4.x?

2019-09-20 07:11 UTC, merged

2019-09-20 09:20 UTC, 7ochem commented on src/Zicht/Bundle/SolrBundle/DependencyInjection/Configuration.php
> +                    ->beforeNormalization()->castToArray()->end()
```suggest
                    ->beforeNormalization()->always(function($v) { return !is_array($v) ? [$v] : $v; })->end()
```