Added DeleteIndexableRelationsInterface to be able to delete related entities in solr
zicht/solr-bundle pull request #54
Opened 2020-06-04 12:48 UTC by cynthiameiring

In case of cascade delete, related entities needs to be deleted in Solr.
(Created together with @7ochem )

Before merging, the CHANGELOG will be updated

2020-06-04 12:51 UTC, wtfzdotnet submitted a review, later dismissed
Interface komt niet overeen met implementatie, last minute refactors? :-)

2020-06-04 13:02 UTC, cynthiameiring commented
> Interface komt niet overeen met implementatie, last minute refactors? :-)

Fixed :+1:

2020-06-04 13:05 UTC, 7ochem commented on src/Zicht/Bundle/SolrBundle/Manager/SolrEntityManager.php
> +use Zicht\Bundle\SolrBundle\Manager\DeleteIndexableRelationsInterface;
Deze is niet nodig. Het is in dezelfde namespace

2020-06-04 13:09 UTC, cynthiameiring commented
Do people have an opinion about whether this a patch or a minor release?

2020-06-04 13:26 UTC, wtfzdotnet commented
I would suggest a minor as it's not a bug-patch :-).

2020-06-08 11:26 UTC, 7ochem approved these changes

2020-06-08 12:42 UTC, 7ochem requested changes
Weet niet precies wat je hebt gedaan, maar wil je je commits even squashen? :tennis:

2020-06-08 13:43 UTC, 7ochem approved these changes

2020-06-08 13:47 UTC, merged